language: python
dist: trusty
sudo: required
services:
- docker
python:
  - 2.7
install:
- docker pull redis # used for testing against
- pip install -r requirements.txt
- pip install -r tests/requirements.txt
script:
  - tox
after_success:
  - codecov
