language: python
dist: trusty
sudo: required
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - travis_retry tests/install_docker.sh
script:
  - tox
after_success:
  - codecov
